export enum QuoteResponse
{
  NOT_REGISTERED='NOT_REGISTERED',
  REGISTERED_AND_AUTHENTICATED='REGISTERED_AND_AUTHENTICATED',
  REGISTERED_NOT_AUTHENTICATED='REGISTERED_NOT_AUTHENTICATED',
  PERMISSION_ID_NO_MATCH='PERMISSION_ID_NO_MATCH',
  PERMISSION_ALREADY_EXISTS='PERMISSION_ALREADY_EXISTS',
  SUCCESS='SUCCESS',
  
}
