export enum RegisterResponse
{
  SUCCESS             = 'SUCCESS',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  USER_NOT_FOUND      = 'USER_NOT_FOUND',
  PASSWORD_POLICY     = 'PASSWORD_POLICY',
  USER_ALREADY_LOGIN  = 'USER_ALREADY_LOGIN',
}