export type QuoteBody = {
	year_car : string,
	first_driving : Date,
	level_car : number,
	energy_car : number,
	color_car : string,
	usage_car : number,
	km_car : number,
	birth : Date,
	start_permis : Date,
	end_permis : Date,
	id_permis : string, 
	fristname : string,
	lastname : string,
	email : string,
	address : string,
	price : number,
	payout_max : number,
	payout_min : number
}